# Generated by Django 4.0.6 on 2022-10-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
